parameters:
    ezpublish.fieldType.keymedia.class: KTQ\Bundle\KeyMediaBundle\FieldType\KeyMedia\Type
    ezpublish.fieldType.keymedia.converter.class: KTQ\Bundle\KeyMediaBundle\FieldType\KeyMedia\Converter
    keymedia_open_graph_handler.field_type.keymedia.class: KTQ\Bundle\KeymediaBundle\OpenGraph\Handler\KeymediaHandler

services:
    ezpublish.fieldType.keymedia:
        class: %ezpublish.fieldType.keymedia.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: keymedia}

    ezpublish.fieldType.keymedia.converter:
        class: %ezpublish.fieldType.keymedia.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: keymedia, lazy: true, callback: '::create'}

    keymedia.twig_extension:
        class: KTQ\Bundle\KeyMediaBundle\Twig\KeymediaExtension
        arguments: [@ezpublish_legacy.kernel, @ezpublish.translation_helper]
        tags:
            - { name: twig.extension }

    keymedia_open_graph_handler.field_type.keymedia:
        class: %keymedia_open_graph_handler.field_type.keymedia.class%
        parent: netgen_open_graph.handler.field_type.abstract
        arguments:
            - @keymedia.twig_extension
            - @?logger
        lazy: true
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/keymedia }